/// Mission Zero content data — compiled from the Gold Standard YAML.
///
/// This map is the Dart representation of `12_sample_mission.yaml`.
/// It is fed directly to [ContentSeeder.seedMission()] at app startup.
///
/// In production with 500+ missions, this will be replaced by a
/// pre-built SQLite database shipped as an asset. For development
/// and the initial vertical slice, inline seeding ensures the
/// content is always available without external file dependencies.
const Map<String, dynamic> missionZeroData = {
  'metadata': {
    'id': 'm01_001_d',
    'title_internal': 'Greeting a Customer on the Phone',
    'title_display_en': 'Your Phone Is Ringing',
    'title_display_de': 'Ihr Telefon klingelt',
    'title_display_darija': 'التيليفون كيصوني',
    'module': 1,
    'sequence': 1,
    'type': 'discovery',
    'estimated_duration_minutes': 25,
    'cefr_level': 'A0',
    'cefr_target': 'A1.1',
    'difficulty': 1,
    'skills': {
      'speaking': 60,
      'listening': 22,
      'vocabulary': 10,
      'pronunciation': 8,
      'reading': 0,
      'writing': 0,
    },
    'career_domains': [
      'phone_communication',
      'customer_greeting',
      'self_presentation',
    ],
    'career_relevance_score': 99,
    'prerequisites': <String>[],
    'tags': [
      'greeting',
      'phone',
      'formal_register',
      'first_contact',
      'module_opener',
      'mission_zero',
      'call_center',
    ],
  },
  'learning_objective': {
    'statement_en':
        'After this mission, the learner can answer a professional phone call in German using the complete call center greeting formula: company name, personal identification, and offer to help.',
    'statement_darija':
        'بعد هاد المهمة، المتعلم يقدر يجاوب على مكالمة احترافية بالألمانية بالصيغة الكاملة ديال call center: اسم الشركة، التعريف بالنفس، وعرض المساعدة.',
  },
  'emotional_goal': {
    'primary_emotion': 'professional_confidence',
    'entry_feeling': 'Nervous but determined — this is what I came here for.',
    'exit_feeling':
        'I just had my first real conversation in German. Professionally.',
    'confidence_vector': 'positive',
    'vulnerability_level': 'moderate',
  },
  'confidence_scoring': {
    'career_readiness_contribution': {
      'domain': 'phone_communication',
      'max_contribution_percent': 3.0,
    },
  },
  'yasmina': {
    'session_greeting': {
      'text_darija':
          'مرحبا بيك. أنا ياسمينا. قبل 5 سنين كنت بحالك بالضبط — ف كازا، كنحلم نخدم ف ألمانيا. اليوم أنا Team Lead ف Düsseldorf. وغادي نعاونك توصل لنفس البلاصة. اليوم: أول مكالمة ديالك. بالألمانية. احترافية. جاهز؟',
      'text_en':
          "Welcome. I'm Yasmina. Five years ago I was exactly where you are — in Casablanca, dreaming of working in Germany. Today I'm a Team Lead in Düsseldorf. Let's get you there. Today: your first call. In German. Professional. Ready?",
    },
    'pre_mission_briefing': {
      'text_darija':
          'شوف — ف call centers الألمانية، ملي كتجاوب على التيليفون عندك صيغة واحدة. ديما نفس الحاجة: تحية + اسم الشركة + سميتك + كيفاش نقدر نعاونك. هادي ماشي اختيارية. كل موظف كيقولها. 50 مرة ف النهار. غادي نتعلموها دابا حتى تولي عندك automatique.',
      'text_en':
          "In German call centers, the phone greeting is a fixed formula. Always the same: greeting + company name + your name + 'How can I help?' Every employee says it. 50 times a day. We're learning it now until it's automatic.",
    },
    'mid_mission_encouragement': {
      'text_en':
          "Good. You just said the full greeting — in German. On your first day. Most learners take a week. You did it in 10 minutes. Now let's use it in a real call.",
      'trigger_after_exercise': 'ex_001_04',
    },
    'post_mission_debrief': {
      'text_darija':
          'شفتي؟ هاد اللي دارتي — جاوبتي على تيليفون بالألمانية، عرفتي بنفسك، سولتي الزبونة على رقم الطلب، شكرتيها. هادا ماشي exercice — هادا professional German communication. غدا: الزبونة غتعاود تقصن. وغتكون جاهز.',
      'text_en':
          "See what you just did? You answered a phone in German, identified yourself, asked for the order number, thanked the customer. That's not an exercise — that's professional German communication. Tomorrow: the customer calls back. And you'll be ready.",
    },
  },

  'vocabulary': {
    'core': [
      {
        'id': 'v_guten_tag',
        'chunk_phrase': 'Guten Tag',
        'functional_meaning':
            'Universal professional greeting in German business. The standard opening for every customer service interaction.',
        'literal_meaning': 'Good day',
        'translation_en': 'Good day (formal greeting)',
        'translation_darija': 'نهاركم مبروك (رسمي)',
        'translation_fr': 'Bonjour (registre formel)',
        'ipa': '/ˈɡuːtn̩ taːk/',
        'audio_native': 'audio/missions/m01_001_d/vocab_guten_tag_native.opus',
        'audio_slow': 'audio/missions/m01_001_d/vocab_guten_tag_slow.opus',
        'register': 'formal',
        'domain': 'greeting',
        'cluster': 'openers',
        'example_in_context': {
          'de': 'Guten Tag, TeleService GmbH, mein Name ist Youssef.',
          'en': 'Good day, TeleService GmbH, my name is Youssef.',
        },
        'srs_config': {
          'initial_interval_hours': 12,
          'initial_ease_factor': 2.5,
          'context_variations': [
            'Guten Tag, hier ist die Serviceabteilung.',
            'Guten Tag, Sie sprechen mit Youssef Ben-Ali.',
            'Guten Tag, wie kann ich Ihnen weiterhelfen?',
            'Guten Tag, herzlich willkommen bei TeleService.',
          ],
        },
      },
      {
        'id': 'v_mein_name_ist',
        'chunk_phrase': 'Mein Name ist...',
        'functional_meaning':
            'Professional self-identification on the phone. The standard call center formula.',
        'translation_en': 'My name is...',
        'translation_darija': 'سميتي... (الصيغة الرسمية)',
        'ipa': '/maɪn ˈnaːmə ɪst/',
        'audio_native': 'audio/missions/m01_001_d/vocab_mein_name_native.opus',
        'audio_slow': 'audio/missions/m01_001_d/vocab_mein_name_slow.opus',
        'register': 'formal',
        'domain': 'identification',
        'cluster': 'openers',
        'example_in_context': {
          'de': 'Mein Name ist Youssef, ich bin Ihr Ansprechpartner.',
          'en': 'My name is Youssef, I am your contact person.',
        },
        'srs_config': {
          'initial_interval_hours': 12,
          'initial_ease_factor': 2.5,
          'context_variations': [
            'Mein Name ist Youssef, wie kann ich helfen?',
            'Guten Tag, mein Name ist Youssef Ben-Ali.',
            'Mein Name ist Youssef, ich kümmere mich um Ihr Anliegen.',
          ],
        },
      },
      {
        'id': 'v_wie_kann_ich_ihnen_helfen',
        'chunk_phrase': 'Wie kann ich Ihnen helfen?',
        'functional_meaning':
            'The standard offer of assistance in German customer service.',
        'literal_meaning': 'How can I you(formal) help?',
        'translation_en': 'How can I help you? (formal)',
        'translation_darija': 'كيفاش نقدر نعاونك؟ (رسمي)',
        'ipa': '/viː kan ɪç ˈiːnən ˈhɛlfn̩/',
        'audio_native': 'audio/missions/m01_001_d/vocab_wie_kann_ich_native.opus',
        'audio_slow': 'audio/missions/m01_001_d/vocab_wie_kann_ich_slow.opus',
        'register': 'formal',
        'domain': 'service_opening',
        'cluster': 'openers',
        'example_in_context': {
          'de': 'Guten Tag, wie kann ich Ihnen heute helfen?',
          'en': 'Good day, how can I help you today?',
        },
        'srs_config': {
          'initial_interval_hours': 12,
          'initial_ease_factor': 2.5,
          'context_variations': [
            'Wie kann ich Ihnen behilflich sein?',
            'Was kann ich für Sie tun?',
            'Wie kann ich Ihnen weiterhelfen?',
          ],
        },
      },
      {
        'id': 'v_selbstverstaendlich',
        'chunk_phrase': 'Selbstverständlich',
        'functional_meaning':
            'Professional affirmation. Communicates willingness to help.',
        'translation_en': 'Of course / Certainly',
        'translation_darija': 'طبعا / بكل تأكيد',
        'ipa': '/ˌzɛlpstfɛɐ̯ˈʃtɛntlɪç/',
        'audio_native':
            'audio/missions/m01_001_d/vocab_selbstverstaendlich_native.opus',
        'audio_slow':
            'audio/missions/m01_001_d/vocab_selbstverstaendlich_slow.opus',
        'register': 'formal',
        'domain': 'affirmation',
        'cluster': 'affirmers',
        'example_in_context': {
          'de': 'Selbstverständlich helfe ich Ihnen gerne.',
          'en': 'Of course, I am happy to help you.',
        },
        'srs_config': {
          'initial_interval_hours': 24,
          'initial_ease_factor': 2.5,
          'context_variations': [
            'Selbstverständlich, das mache ich sofort.',
            'Selbstverständlich helfe ich Ihnen gerne.',
            'Selbstverständlich, Frau Schmidt. Einen Moment bitte.',
          ],
        },
      },
      {
        'id': 'v_einen_moment_bitte',
        'chunk_phrase': 'Einen Moment bitte',
        'functional_meaning':
            'Professional time-buyer. Fills silence while checking information.',
        'translation_en': 'One moment please',
        'translation_darija': 'لحظة عافاك',
        'ipa': '/ˈaɪnən moˈmɛnt ˈbɪtə/',
        'audio_native': 'audio/missions/m01_001_d/vocab_einen_moment_native.opus',
        'audio_slow': 'audio/missions/m01_001_d/vocab_einen_moment_slow.opus',
        'register': 'formal',
        'domain': 'call_management',
        'cluster': 'bridges',
        'example_in_context': {
          'de': 'Einen Moment bitte, ich schaue in unserem System nach.',
          'en': "One moment please, I'll look it up in our system.",
        },
        'srs_config': {
          'initial_interval_hours': 12,
          'initial_ease_factor': 2.5,
          'context_variations': [
            'Einen Moment bitte, ich prüfe das für Sie.',
            'Einen kleinen Moment, ich verbinde Sie.',
            'Einen Moment, ich schaue sofort nach.',
          ],
        },
      },
    ],
    'supporting': <Map<String, dynamic>>[],
    'review': <Map<String, dynamic>>[],
  },

  'dialogue': {
    'id': 'dlg_m01_001',
    'context': 'First customer call — Frau Schmidt asks about her order',
    'total_turns': 8,
    'turns': [
      {
        'turn': 1,
        'speaker': 'system',
        'type': 'narration',
        'text_en': 'Your headset beeps twice. Incoming call from Frau Schmidt. Answer now.',
      },
      {
        'turn': 2,
        'speaker': 'agent',
        'type': 'production',
        'text_de': 'Guten Tag, TeleService GmbH, mein Name ist Youssef, wie kann ich Ihnen helfen?',
        'text_de_slow': 'Guten Tag... TeleService GmbH... mein Name ist Youssef... wie kann ich Ihnen helfen?',
        'translation_en': 'Good day, TeleService GmbH, my name is Youssef, how can I help you?',
        'translation_darija': 'نهار مبروك، تيلي سيرفيس، سميتي يوسف، كيفاش نقدر نعاونكم؟',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t2_native.opus',
        'audio_path_slow': 'audio/missions/m01_001_d/dlg_t2_slow.opus',
        'acceptable_responses': [
          {'pattern': 'Guten Tag', 'required': true, 'weight': 0.20},
          {'pattern': 'wie kann ich', 'required': true, 'weight': 0.25},
          {'pattern': 'helfen', 'required': true, 'weight': 0.30},
          {'pattern': 'Name', 'required': false, 'weight': 0.15},
        ],
        'pronunciation_notes': [
          {'segment': 'Guten Tag', 'note': 'GU-ten TAG. Confident, not tentative.'},
          {'segment': 'Ihnen helfen?', 'note': 'Rising intonation on helfen? — question.'},
        ],
      },
      {
        'turn': 3,
        'speaker': 'frau_schmidt',
        'type': 'input',
        'text_de': 'Oh, guten Tag! Hier ist Schmidt. Ich habe eine Frage zu meiner Bestellung.',
        'translation_en': 'Good day! This is Schmidt. I have a question about my order.',
        'translation_darija': 'نهار مبروك! أنا شميت. عندي سؤال على الكوموند ديالي.',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t3_native.opus',
        'audio_path_slow': 'audio/missions/m01_001_d/dlg_t3_slow.opus',
        'comprehension_check': {
          'options': [
            {'text_en': 'She has a question about her order', 'correct': true},
            {'text_en': 'She wants to complain', 'correct': false},
            {'text_en': 'She wants to cancel', 'correct': false},
          ],
        },
      },
      {
        'turn': 4,
        'speaker': 'agent',
        'type': 'production',
        'text_de': 'Selbstverständlich, Frau Schmidt. Können Sie mir bitte Ihre Bestellnummer nennen?',
        'translation_en': 'Of course, Mrs. Schmidt. Could you please give me your order number?',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t4_native.opus',
        'audio_path_slow': 'audio/missions/m01_001_d/dlg_t4_slow.opus',
        'acceptable_responses': [
          {'pattern': 'Selbstverständlich', 'required': false, 'weight': 0.20},
          {'pattern': 'Bestellnummer', 'required': true, 'weight': 0.40},
          {'pattern': 'bitte', 'required': false, 'weight': 0.20},
        ],
      },
      {
        'turn': 5,
        'speaker': 'frau_schmidt',
        'type': 'input',
        'text_de': 'Ja, natürlich. Die Nummer ist 4-7-3-8-2.',
        'translation_en': 'Yes, of course. The number is 4-7-3-8-2.',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t5_native.opus',
      },
      {
        'turn': 6,
        'speaker': 'agent',
        'type': 'production',
        'text_de': 'Vielen Dank, Frau Schmidt. Einen Moment bitte, ich schaue in unserem System nach.',
        'translation_en': 'Thank you, Mrs. Schmidt. One moment please, I will look it up.',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t6_native.opus',
        'audio_path_slow': 'audio/missions/m01_001_d/dlg_t6_slow.opus',
        'acceptable_responses': [
          {'pattern': 'Dank', 'required': true, 'weight': 0.20},
          {'pattern': 'Moment', 'required': true, 'weight': 0.30},
          {'pattern': 'schaue', 'required': false, 'weight': 0.25},
        ],
      },
      {
        'turn': 7,
        'speaker': 'frau_schmidt',
        'type': 'input',
        'text_de': 'Ja, kein Problem. Ich warte.',
        'translation_en': 'Yes, no problem. I will wait.',
        'audio_path_native': 'audio/missions/m01_001_d/dlg_t7_native.opus',
      },
      {
        'turn': 8,
        'speaker': 'system',
        'type': 'narration',
        'text_en': 'Frau Schmidt is waiting. You handled the opening perfectly. Mission complete.',
      },
    ],
  },

  'exercises': [
    {
      'id': 'ex_001_01',
      'type': 'listenComprehend',
      'order': 1,
      'phase': 'ignite',
      'prompt_text_en': 'Listen to this professional phone greeting. Notice the four parts.',
      'prompt_text_darija': 'سمع هاد التحية المهنية. لاحظ الأربع أجزاء.',
      'target_text_de': 'Guten Tag, TeleService GmbH, mein Name ist Anna Becker, wie kann ich Ihnen helfen?',
      'target_audio_native': 'audio/missions/m01_001_d/ex01_full_greeting_native.opus',
      'evaluation_mode': 'comprehensionCheck',
      'evaluation_config': {
        'minimum_score': 0.5,
        'options': [
          {'text_en': 'Four: greeting + company + name + offer to help', 'correct': true},
          {'text_en': 'Two: hello + name', 'correct': false},
          {'text_en': 'One: just a greeting', 'correct': false},
        ],
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': false, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'Exactly. Four parts. That is the German call center formula.',
        'on_partial': 'Listen again — four distinct parts in that greeting.',
        'on_retry': 'The formula: Greeting + Company + Name + How can I help?',
      },
      'max_attempts': 2,
      'estimated_duration_seconds': 45,
      'vocabulary_ids': <String>[],
      'srs_trigger': false,
    },
    {
      'id': 'ex_001_02',
      'type': 'shadow',
      'order': 2,
      'phase': 'ignite',
      'prompt_text_en': 'Part 1 of the formula. Listen and repeat: the greeting.',
      'target_text_de': 'Guten Tag',
      'target_audio_native': 'audio/missions/m01_001_d/vocab_guten_tag_native.opus',
      'target_audio_slow': 'audio/missions/m01_001_d/vocab_guten_tag_slow.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.40,
        'keywords_required': ['Guten', 'Tag'],
        'pronunciation_weight': 0.7,
        'completeness_weight': 0.3,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true, 'hint_available': true},
        'support_standard': {'text_visible': true, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'Clean. That is your professional hello.',
        'on_partial': 'Close! The T in Tag is strong.',
        'on_retry': 'Listen once more. GU-ten TAG. Two beats.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 40,
      'vocabulary_ids': ['v_guten_tag'],
      'srs_trigger': true,
    },
    {
      'id': 'ex_001_03',
      'type': 'shadow',
      'order': 3,
      'phase': 'equip',
      'prompt_text_en': 'Part 3 — your identification. Listen and repeat.',
      'target_text_de': 'Mein Name ist Youssef',
      'target_audio_native': 'audio/missions/m01_001_d/vocab_mein_name_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.40,
        'keywords_required': ['Name'],
        'keywords_optional': ['Mein', 'ist'],
        'pronunciation_weight': 0.6,
        'completeness_weight': 0.4,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': true, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'Professional identification. That replaces casual Ich bin.',
        'on_partial': 'Mein rhymes with English mine. MINE Nah-muh ist...',
        'on_retry': 'Break it: MEIN... NAH-muh... ist... your name.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 50,
      'vocabulary_ids': ['v_mein_name_ist'],
      'srs_trigger': true,
    },
    {
      'id': 'ex_001_04',
      'type': 'shadow',
      'order': 4,
      'phase': 'equip',
      'prompt_text_en': 'Part 4 — the most important part. The offer to help.',
      'target_text_de': 'Wie kann ich Ihnen helfen?',
      'target_audio_native': 'audio/missions/m01_001_d/vocab_wie_kann_ich_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.40,
        'keywords_required': ['kann', 'helfen'],
        'keywords_optional': ['Wie', 'ich', 'Ihnen'],
        'pronunciation_weight': 0.6,
        'completeness_weight': 0.4,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': true, 'audio_model_first': false},
        'support_minimal': {'text_visible': false, 'audio_model_first': false},
      },
      'feedback': {
        'on_success': 'That is the core. You will say this 50 times a day at work.',
        'on_partial': 'Rise at the end — it is a question. helfen?',
        'on_retry': 'Two halves: Wie kann ich — Ihnen helfen?',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 60,
      'vocabulary_ids': ['v_wie_kann_ich_ihnen_helfen'],
      'srs_trigger': true,
    },
    {
      'id': 'ex_001_05',
      'type': 'reconstruct',
      'order': 5,
      'phase': 'equip',
      'prompt_text_en': 'Now — the full formula. All four parts together.',
      'target_text_de': 'Guten Tag, TeleService GmbH, mein Name ist Youssef, wie kann ich Ihnen helfen?',
      'target_audio_native': 'audio/missions/m01_001_d/dlg_t2_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.40,
        'keywords_required': ['Guten', 'Tag', 'Name', 'helfen'],
        'keywords_optional': ['TeleService', 'kann', 'ich', 'Ihnen'],
        'pronunciation_weight': 0.4,
        'completeness_weight': 0.6,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': false, 'audio_model_first': true, 'hint_available': true, 'hint_text': 'Greeting + Company + Name + How can I help?'},
        'support_minimal': {'text_visible': false, 'audio_model_first': false},
      },
      'feedback': {
        'on_success': 'That is a complete professional greeting. In German. Built from zero.',
        'on_partial': 'Good structure. Try two breaths: first half, then second half.',
        'on_retry': 'Start with just: Guten Tag, TeleService GmbH. Get that solid first.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 75,
      'vocabulary_ids': ['v_guten_tag', 'v_mein_name_ist', 'v_wie_kann_ich_ihnen_helfen'],
      'srs_trigger': false,
    },
    {
      'id': 'ex_001_06',
      'type': 'vocabularyPresent',
      'order': 6,
      'phase': 'equip',
      'prompt_text_en': 'New phrase: Selbstverständlich — the professional of course.',
      'target_text_de': 'Selbstverständlich',
      'target_audio_native': 'audio/missions/m01_001_d/vocab_selbstverstaendlich_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.35,
        'keywords_required': ['Selbstverständlich'],
        'pronunciation_weight': 0.7,
        'completeness_weight': 0.3,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true, 'hint_available': true, 'hint_text': 'SELBST-ver-STÄND-lich. Four beats.'},
        'support_standard': {'text_visible': true, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'Beautiful. That word makes you sound experienced.',
        'on_partial': 'SELBST-ver-STÄND-lich. Four syllables. Try beat by beat.',
        'on_retry': 'Four syllables, two stresses: SELBST and STÄND.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 60,
      'vocabulary_ids': ['v_selbstverstaendlich'],
      'srs_trigger': true,
    },
    {
      'id': 'ex_001_07',
      'type': 'vocabularyPresent',
      'order': 7,
      'phase': 'equip',
      'prompt_text_en': 'One more tool: Einen Moment bitte — buys you time.',
      'target_text_de': 'Einen Moment bitte',
      'target_audio_native': 'audio/missions/m01_001_d/vocab_einen_moment_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.40,
        'keywords_required': ['Moment'],
        'keywords_optional': ['Einen', 'bitte'],
        'pronunciation_weight': 0.6,
        'completeness_weight': 0.4,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': true, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'Perfect. Fills silence professionally.',
        'on_partial': 'mo-MENT — stress on second syllable.',
        'on_retry': 'EYE-nen mo-MENT BIT-tuh. Three words.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 50,
      'vocabulary_ids': ['v_einen_moment_bitte'],
      'srs_trigger': true,
    },
    {
      'id': 'ex_001_08',
      'type': 'conversation',
      'order': 8,
      'phase': 'challenge',
      'prompt_text_en': 'Your phone is ringing. Handle the complete call with Frau Schmidt.',
      'dialogue_id': 'dlg_m01_001',
      'evaluation_mode': 'dialogueCompletion',
      'evaluation_config': {
        'minimum_score': 0.40,
        'dialogue_id': 'dlg_m01_001',
        'weight_per_turn': {'turn_2': 0.40, 'turn_4': 0.35, 'turn_6': 0.25},
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true, 'hint_available': true},
        'support_standard': {'text_visible': false, 'first_words_visible': true, 'first_words': ['Guten...', 'Selbst...', 'Vielen...'], 'hint_available': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': false},
      },
      'feedback': {
        'on_success': 'You just handled your first customer call. In German. Professionally.',
        'on_success_darija': 'تعاملتي مع أول مكالمة زبون ديالك. بالألمانية. باحترافية.',
        'on_partial': 'The call got handled. Some phrases to polish — they will come back.',
        'on_retry': 'Let us try with more support this time.',
      },
      'max_attempts': 2,
      'estimated_duration_seconds': 180,
      'vocabulary_ids': ['v_guten_tag', 'v_mein_name_ist', 'v_wie_kann_ich_ihnen_helfen', 'v_selbstverstaendlich', 'v_einen_moment_bitte'],
      'srs_trigger': false,
    },
    {
      'id': 'ex_001_09',
      'type': 'repeat',
      'order': 9,
      'phase': 'land',
      'prompt_text_en': 'One last time. Your professional greeting. From memory.',
      'target_text_de': 'Guten Tag, TeleService GmbH, mein Name ist Youssef, wie kann ich Ihnen helfen?',
      'target_audio_native': 'audio/missions/m01_001_d/dlg_t2_native.opus',
      'evaluation_mode': 'pronunciationMatch',
      'evaluation_config': {
        'minimum_score': 0.45,
        'keywords_required': ['Guten', 'Tag', 'Name', 'helfen'],
        'pronunciation_weight': 0.5,
        'completeness_weight': 0.5,
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': false},
        'support_standard': {'text_visible': false, 'hint_available': true, 'hint_text': 'Four parts: Greeting + Company + Name + Offer'},
        'support_minimal': {'text_visible': false, 'audio_model_first': false},
      },
      'feedback': {
        'on_success': 'Automatic. That is what we are building.',
        'on_partial': 'Getting there. Each time smoother.',
        'on_retry': 'You know this. Breathe, then say it like you own it.',
      },
      'max_attempts': 3,
      'estimated_duration_seconds': 50,
      'vocabulary_ids': ['v_guten_tag', 'v_wie_kann_ich_ihnen_helfen'],
      'srs_trigger': false,
    },
    {
      'id': 'ex_001_10',
      'type': 'listenComprehend',
      'order': 10,
      'phase': 'land',
      'prompt_text_en': 'Final check: Frau Schmidt calls again. What does she say?',
      'target_text_de': 'Guten Tag! Hier ist Schmidt. Ich habe eine Frage zu meiner Bestellung.',
      'target_audio_native': 'audio/missions/m01_001_d/dlg_t3_native.opus',
      'evaluation_mode': 'comprehensionCheck',
      'evaluation_config': {
        'minimum_score': 0.5,
        'options': [
          {'text_en': 'Help with her order', 'correct': true},
          {'text_en': 'To make a complaint', 'correct': false},
          {'text_en': 'To speak with a manager', 'correct': false},
        ],
      },
      'scaffolding': {
        'support_high': {'text_visible': true, 'audio_model_first': true},
        'support_standard': {'text_visible': false, 'audio_model_first': true},
        'support_minimal': {'text_visible': false, 'audio_model_first': true},
      },
      'feedback': {
        'on_success': 'You understood her at natural speed. Listening builds alongside speaking.',
        'on_partial': 'Key word: Bestellung (order). That tells you what she needs.',
        'on_retry': 'Ich habe eine Frage zu meiner Bestellung = I have a question about my order.',
      },
      'max_attempts': 2,
      'estimated_duration_seconds': 40,
      'vocabulary_ids': <String>[],
      'srs_trigger': false,
    },
  ],
};
